# copy a file from the local machine or remote machine to a location on a managed hosts. Similar to the file module, the copy module can also set file attribute including selinux context.
---
-  name: using the copy module
   hosts: node1
   tasks:
   -  name: copy a file managed hosts and set attributes
      ansible.builtin.copy:
      src: work.txt 
      state: /home/rajat/work.txt
      owner: bob
      group: student
      mode: u+rw,g-wx,o-rwx
      setype: samba_share_t
